### ISSUE TITLE
Install instructions/can't get it to work

### ISSUE THREAD

**Issue by AshKyd** [mafintosh/wat2js#2]
Hey, this looks like fun. Can't get it to work with these instructions though.

The readme says `Currently requires the wast2wasm program to be installed globally` but index.js tries to spawn `wat2wasm` which is different. I can't work out how to install either.

Got any pointers? :)

**Comment by emilbayes** [comment]
You can install `wat2wasm` with https://github.com/mafintosh/webassembly-binary-toolkit or DIY by following the [MDN guide](https://developer.mozilla.org/en-US/docs/WebAssembly/Text_format_to_wasm)

**Comment by mafintosh** [comment]
Fixed in the readme :)
